-
  name: 'QR Code Archive'
  uriPattern: 'neosidekick/qrcode/archive'
  defaults:
    '@package': 'NEOSidekick.QRCode'
    '@controller': 'QrCodeArchive'
    '@action': 'downloadAll'
  appendExceedingArguments: TRUE
  httpMethods: ['GET']

-
  name: 'QR Code Generator'
  uriPattern: 'neosidekick/qrcode'
  defaults:
    '@package': 'NEOSidekick.QRCode'
    '@controller': 'QrCode'
    '@action': 'index'
  appendExceedingArguments: TRUE
