NEOSidekick:
  QRCode:
    version: 10
    eccLevel: 'H'
    moduleShape: 'round'
    archive:
      enabled: false
    themes:
      grey:
        color: 'rgb(237, 237, 237)'
      black:
        color: '#000'

Neos:
  Neos:
    fusion:
      autoInclude:
        NEOSidekick.QRCode: true
  Fusion:
    defaultContext:
      NEOSidekickQRCode: NEOSidekick\QRCode\QrCodeHelper
  Flow:
    security:
      authentication:
        providers:
          'Neos.Neos:Backend':
            requestPatterns:
              'NEOSidekick.QRCode:Controllers':
                pattern: 'ControllerObjectName'
                patternOptions:
                  controllerObjectNamePattern: 'NEOSidekick\QRCode\Controller\.*'
    mvc:
      routes:
        'NEOSidekick.QRCode':
          position: 'before Neos.Neos'
