NEOSidekick:
  QRCode:
    version: 10
    eccLevel: 'H'
    moduleShape: 'round'
    themes:
      grey:
        color: 'rgb(237, 237, 237)'
      black:
        color: '#000'

Neos:
  Neos:
    fusion:
      autoInclude:
        NEOSidekick.QRCode: true
  Fusion:
    defaultContext:
      NEOSidekickQRCode: NEOSidekick\QRCode\QrCodeHelper
  Flow:
    mvc:
      routes:
        'NEOSidekick.QRCode':
          position: 'before Neos.Neos'
